parameters:
    default_sender_name: '%env(DEFAULT_SENDER_NAME)%'
    default_sender_mail: '%env(DEFAULT_SENDER_MAIL)%'
    admin_email: '%env(ADMIN_EMAIL)%'

services:
    Alengo\Bundle\AlengoCacheWarmupBundle\Service\CacheWarmupService:
        autowire: true
        autoconfigure: true

    Alengo\Bundle\AlengoCacheWarmupBundle\EventSubscriber\CacheWarmupSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
        autowire: true
        autoconfigure: true

    Alengo\Bundle\AlengoCacheWarmupBundle\MessageHandler\SitemapCacheWarmupHandler:
        arguments:
            $cacheWarmupService: '@Alengo\Bundle\AlengoCacheWarmupBundle\Service\CacheWarmupService'
            $mailer: '@mailer'
            $defaultSenderName: '%default_sender_name%'
            $defaultSenderMail: '%default_sender_mail%'
            $adminEmail: '%admin_email%'
        autowire: true
        autoconfigure: true